### ISSUE TITLE
Dead link discovered in README.md

### ISSUE THREAD

**Issue by linux-lukas** [pintman/scripts#1]
The reference to the Ansible documentation at [this link here](https://github.com/pintman/scripts/tree/master/rpi_admin), specifically, the link in this sentence: *"The setup.yml file contains what is called a playbook, which is used to prepare the machines."* The call to the page fails, with the error message: *"The version of Ansible documentation you were looking at does not contain this page. "*. 

It is likely that the documentation was changed to the point where the link became a dead link.

**Comment by pintman** [comment]
Das Problem lässt sich sicher leicht lösen. Magst du einen PR erstellen?

**Comment by linux-lukas** [comment]
Pull request has been made.
